// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/FamCan-RiskAssessment/Backend/bootstrap"
	"github.com/FamCan-RiskAssessment/Backend/internal/infrastructure/database"
	"github.com/FamCan-RiskAssessment/Backend/internal/presentation/middleware"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApplication(config *bootstrap.Config) (*Application, error) {
	bootstrapDatabase := ProvideDBConfig(config)
	postgresDatabase := database.NewPostgresDatabase(bootstrapDatabase)
	wireDatabase := &Database{
		DB: postgresDatabase,
	}
	constants := ProvideConstants(config)
	recoveryMiddleware := middleware.NewRecoveryMiddleware(constants)
	middlewares := &Middlewares{
		Recovery: recoveryMiddleware,
	}
	application := NewApplication(wireDatabase, middlewares)
	return application, nil
}

// wire.go:

var DatabaseProviderSet = wire.NewSet(database.NewPostgresDatabase, wire.Bind(new(database.Database), new(*database.PostgresDatabase)), wire.Struct(new(Database), "*"))

var MiddlewareProviderSet = wire.NewSet(middleware.NewRecoveryMiddleware, wire.Struct(new(Middlewares), "*"))

func ProvideDBConfig(container *bootstrap.Config) *bootstrap.Database {
	return &container.Env.Database
}

func ProvideConstants(container *bootstrap.Config) *bootstrap.Constants {
	return container.Constants
}

var ProviderSet = wire.NewSet(
	DatabaseProviderSet,
	MiddlewareProviderSet,
	ProvideDBConfig,
	ProvideConstants,
)

type Database struct {
	DB database.Database
}

type Middlewares struct {
	Recovery *middleware.RecoveryMiddleware
}

type Application struct {
	Database    *Database
	Middlewares *Middlewares
}

func NewApplication(database2 *Database,
	middlewares *Middlewares,
) *Application {
	return &Application{
		Database:    database2,
		Middlewares: middlewares,
	}
}
