// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/FamCan-RiskAssessment/Backend/bootstrap"
	"github.com/FamCan-RiskAssessment/Backend/internal/infrastructure/database"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApplication(config *bootstrap.Config) (*Application, error) {
	bootstrapDatabase := ProvideDBConfig(config)
	postgresDatabase := database.NewPostgresDatabase(bootstrapDatabase)
	wireDatabase := &Database{
		DB: postgresDatabase,
	}
	application := NewApplication(wireDatabase)
	return application, nil
}

// wire.go:

var DatabaseProviderSet = wire.NewSet(database.NewPostgresDatabase, wire.Bind(new(database.Database), new(*database.PostgresDatabase)), wire.Struct(new(Database), "*"))

func ProvideDBConfig(container *bootstrap.Config) *bootstrap.Database {
	return &container.Env.Database
}

var ProviderSet = wire.NewSet(
	DatabaseProviderSet,
	ProvideDBConfig,
)

type Database struct {
	DB database.Database
}

type Application struct {
	Database *Database
}

func NewApplication(database2 *Database,
) *Application {
	return &Application{
		Database: database2,
	}
}
