package localization

var Persian = map[string]interface{}{
	"OTP":                 "رمز یکبار مصرف",
	"form":                "فرم",
	"firstName":           "نام",
	"lastName":            "نام خانوادگی",
	"phone":               "شماره تماس",
	"password":            "رمز عبور",
	"confirmPassword":     "تایید رمز عیور",
	"isAcceptTerms":       "تایید شرایط و مقررات",
	"nationalID":          "شناسه ملی",
	"user":                "کاربر",
	"address":             "آدرس",
	"name":                "نام",
	"province":            "استان",
	"city":                "شهر",
	"page":                "صفحه",
	"contactType":         "راه ارتباطی",
	"room":                "اتاق گفتگو",
	"notificationType":    "نوع اعلانات",
	"notificationTypes":   "نوع اعلانات",
	"notification":        "اعلان",
	"NotificationSetting": "تنظیمات اعلان",
	"email":               "ایمیل",
	"ticket":              "درخواست پشتیبانی",
	"role":                "نقش",
	"permission":          "دسترسی",
	"record":              "رکورد",
	"mamography_info":     "داده های ماموگرافی",
	"family_cancer_info":  "داده های مرتبط با سرطان خانوادگی",
	"ticketComment":       "نظر در مورد درخواست پشتیبانی",
	"report":              "گزارش",
	"contactInformation":  "پل ارتباطی",
	"tittle":              "عنوان",
	"media":               "محتوا",
	"cancer":              "سرطان",
	"errors": map[string]interface{}{
		"generic":                "خطایی رخ داده است، لطفا دوباره تلاش کنید.",
		"numeric":                "`{0}` باید عدد باشد.",
		"fileRequired":           "وارد کردن فایل اجباری است.",
		"minimumLength":          "باید از 7 کاراکتر بیشتر باشد.",
		"containsLowercase":      "باید حتما دارای حرف کوچک باشد.",
		"containsUppercase":      "باید حتما دارای حرف بزرگ باشد.",
		"containsNumber":         "باید حتما دارای عدد باشد.",
		"containsSpecialChar":    "باید حتما دارای حروف خاص باشد.",
		"alreadyRegistered":      "قبلا با این {0} ثبت نام کرده است.",
		"required":               "بخش {0} باید کامل شود.",
		"e164":                   "شماره تلفن به درستی ثبت نشده است.",
		"eqfield":                "رمز عبور و {0} مطابقت ندارند.",
		"eq":                     "مقدار {0 باید درست باشد}",
		"expired":                "رمز یکبار مصرف شما منقضی شده است.",
		"invalid":                "رمز یکبار مصرف وارد شده اشتباه است.",
		"notRegistered":          "ابتدا باید در سایت ثبت نام کنید.",
		"invalidAuthCredentials": "نام کاربری و رمز عبور تطابق ندارند.",
		"expiredAuthToken":       "نشست شما منقضی شده است. لطفا دوباره وارد شوید.",
		"invalidAuthToken":       "در توکن ورود شما اشکالی وجود دارد.",
		"unauthorized":           "ابتدا باید وارد شوید.",
		"awaitingApproval":       "حساب شما در انتظار تایید ادمین است.",
		"rejected":               "حساب شما توسط ادمین رد شده است.",
		"notExist":               "این {0} وجود ندارد.",
		"alreadyExist":           "این {0} قبلا وجود داشته است.",
		"notFound":               "این {0} پیدا نشد.",
		"notVerified":            "باید ابتدا حساب خود را فعال کنید.",
		"notActive":              "این {0} فعال نیست.",
		"rateLimitExceed":        "بیشتر از حد مجاز درخواست ثبت کرده اید.",
		"installRateLimit":       "تعداد درخواست های فعال شما از حدنساب عبور کرده است.",
		"forbiddenError":         "اجازه دسترسی به این {0} وجود ندارد.",
		"forbiddenStatus":        "اجازه انجام این کار را در این وضعیت ندارید.",
		"pending":                "این {0} حال بررسی است.",
		"email":                  "فرمت ایمیل نادرست است.",
		"alreadyBlocked":         "این {0} از پیش مسدود شده است.",
		"alreadyActive":          "این {0} از پیش فعال شده است.",
		"alreadyResolved":        "این {0} قبلا بررسی شده است.",
		"alreadyArchived":        "این {0} قبلا آرشیو شده است.",
		"statusNotChange":        "این {0} قبلا همین وضعیت را داشته است.",
		"alreadyCanceled":        "این {0} قبلا لغو شده است.",
		"alreadyRejected":        "این {0} قبلا رد شده است.",
		"alreadyAccepted":        "این {0} قبلا قبول شده است.",
		"alreadyDraft":           "این {0} قبلا در حالت پیش نویس قرار گرفته است.",
	},
	"successMessage": map[string]interface{}{
		"userRegister":              "ثبت نام موفق بود! لطفاً پیامک های خود را بررسی کنید تا حساب خود را تأیید کرده و فرآیند ثبت نام را تکمیل نمایید.",
		"phoneVerification":         "شماره شما با موفقیت تایید شد.",
		"login":                     "شما با موفقیت وارد شدید.",
		"changePassword":            "رمز عبور با موفقیت تغییر کرد.",
		"forgotPassword":            "لطفا پیامک های خود را بررسی کنید تا تلفن خود را تایید نمایید .",
		"resetPassword":             "گذرواژه با موفقیت تغییر کرد.",
		"refreshToken":              "نشست شما با موفقیت تمدید شد.",
		"addCorporationCertificate": "مدارک شما با موفقیت آپلود شد.",
		"readNotification":          "اعلان با موفقیت خوانده شد.",
		"updateNotificationSetting": "تنظیمات اعلان های شما به روزرسانی شد.",
		"createTicket":              "درخواست شما با موفقیت ثبت شد.",
		"createTicketComment":       "نظر شما با موفقیت ثبت شد.",
		"blockChatRoom":             "اتاق گفتگو با موفقیت مسدود شد.",
		"unblockChatRoom":           "اتاق گفتگو با موفقیت رفع مسدود شد.",
		"createRole":                "نقش جدید با موفقیت ساخته شد.",
		"deleteRole":                "نقش مورد نظر با موفقیت حذف شد..",
		"updateRole":                "نقش مورد نظر با موفقیت به روزرسانی شد.",
		"updateUserRoles":           "نقش های فرد مورد نظر به روزرسانی شد.",
		"ticketResolved":            "درخواست پشتیبانی با موفقیت بررسی شد.",
		"createReport":              "گزارش شما با موفقیت ثبت شد.",
		"reportResolved":            "گزارش شما با موفقیت بررسی شد.",
		"banUser":                   "کاربر با موفقیت محدود شد.",
		"unbanUser":                 "کاربر با موفقیت رفع محدود شد.",
		"addMedia":                  "محتوای مورد نظر با موفقیت آپلود شد.",
		"deleteMedia":               "محتوای مورد نظر با موفقیت حذف شد.",
		"createForm":                "فرم شما با موفقیت ثبت شد.",
		"updateForm":                "فرم شما با موفقیت به روز رسانی شد.",
		"deleteForm":                "فرم شما با موفقیت حذف شد.",
		"setPassword":               "پسورد شما با موفقیت تنظیم شد.",
		"sendOTP":                   "کد پیامکی ارسال شد.",
		"acceptForm":                "فرم شما با موفقیت قبول شد.",
		"rejectForm":                "فرم شما با موفقیت رد شد.",
	},
	"emailSubject": map[string]interface{}{
		"emailConfirmation": "تأیید آدرس ایمیل شما",
	},
}
